[Font]
editor = {
	name = "Fira Code",
	size = 14 }
	
ui = {
	name = "Fira Sans",
	size = 14 }
	


[Tool]
desc = "build project"
cmd = "pwsh.exe -f .\build.ps1"
open-console = "on-start"




