[Font]
editor = {
	name = "Geist Mono",
	size = 14 }
	
ui = {
	name = "Geist",
	size = 14 }
	


[[Tools]]
name = "build project"
command = 'pwsh.exe -f .\build.ps1'
open-console = "on-start"

