[Font]
editor = {
	#name = "Geist Mono",
	name = "Fira Code",
	size = 12}
	
ui = {
	#name = "Geist",
	name = "Fira Sans",
	size = 12}
	


[[Tools]]
name = "build project"
command = 'pwsh.exe -f .\build.ps1 %0 %1 %2'
open-console = "on-start"
diagnostics = {
	regex = '^([A-Z]:[\w\.\\-]+)\((\d+)\): (\w+)(?: C\d+)?: .*$',
	group-file = 1,
	group-line = 2,
	group-color = 3,
	color-mapping = {
		error   = [255, 0, 0],
		warning = [255, 255, 0],
		note    = [0, 255, 0]}}
parameters = [
	{
		type = "enum",
		name = "profile",
		default = "debug",
		values = [
			"debug",
			"stable",
			"release"
		]
	},
	{
		type = "bool",
		name = "reconfigure",
		default = false,
		if-true = "-reconfigure",
		if-false = ""
	},
	{
		type = "bool",
		name = "run",
		default = true,
		if-true = "-runDetached",
		if-false = ""
	}
]

# @TODO make parameter for PWD so we don't need to do the pwsh hack
#[[Tools]]
#name = "dnGREP"
#command = 'pwsh -c Start-Process -Path D:\Apps\dnGrep\dnGrep.exe -ArgumentList $PWD'
#open-console = "never"

#[[Tools]]
#name = "edit TODO.md"
#command = "marktext .\TODO.md"
#open-console = "never"

[[Tools]]
name = "test tool"
command = 'pwsh.exe -f .\test\testtool.ps1 %0'
open-console = "on-start"
progress = {
	regex = '^\[(\d+|X+)/(\d+)\]',
	group-value = 1,
	group-max = 2}
diagnostics = {
	regex = '^([A-Z]:[\w\.\\-]+)\((\d+)\): (\w+)(?: C\d+)?: .*$',
	group-file = 1,
	group-line = 2,
	group-color = 3,
	color-mapping = {
		error   = [255, 0, 0],
		warning = [255, 255, 0],
		note    = [0, 255, 0]}}
parameters = [
	{
		type = "bool",
		name = "skip delays",
		default = false,
		if-true = "-skipDelays",
		if-false = ""
	}
]