#pragma once

#define ICON_UNKNOWN 0
#define ICON_WAITING 1
#define ICON_ERROR   2
#define ICON_NOITEMS 3
	 
#define ICON_TABS_MODIFIEDHOVERED 4
#define ICON_TABS_MODIFIED 5
#define ICON_TABS_HOVERED 6
	 
#define ICON_EDITORDIAGNOSTICS_ERROR 7 
#define ICON_EDITORDIAGNOSTICS_WARNING 8
#define ICON_EDITORDIAGNOSTICS_INFO 9
#define ICON_EDITORDIAGNOSTICS_HINT 10
#define ICON_EDITORAUTOCOMPLETE_TEXT 11
#define ICON_EDITORAUTOCOMPLETE_METHOD 12
#define ICON_EDITORAUTOCOMPLETE_FUNCTION 13
#define ICON_EDITORAUTOCOMPLETE_CONSTRUCTOR 14
#define ICON_EDITORAUTOCOMPLETE_FIELD 15
#define ICON_EDITORAUTOCOMPLETE_VARIABLE 16
#define ICON_EDITORAUTOCOMPLETE_CLASS 17
#define ICON_EDITORAUTOCOMPLETE_INTERFACE 18
#define ICON_EDITORAUTOCOMPLETE_MODULE 19
#define ICON_EDITORAUTOCOMPLETE_PROPERTY 20
#define ICON_EDITORAUTOCOMPLETE_UNIT 21
#define ICON_EDITORAUTOCOMPLETE_VALUE 22
#define ICON_EDITORAUTOCOMPLETE_ENUM 23
#define ICON_EDITORAUTOCOMPLETE_KEYWORD 24
#define ICON_EDITORAUTOCOMPLETE_SNIPPET 25
#define ICON_EDITORAUTOCOMPLETE_COLOR 26
#define ICON_EDITORAUTOCOMPLETE_FILE 27
#define ICON_EDITORAUTOCOMPLETE_REFERENCE 28
#define ICON_EDITORAUTOCOMPLETE_FOLDER 29
#define ICON_EDITORAUTOCOMPLETE_ENUMMEMBER 30
#define ICON_EDITORAUTOCOMPLETE_CONSTANT 31
#define ICON_EDITORAUTOCOMPLETE_STRUCT 32
#define ICON_EDITORAUTOCOMPLETE_EVENT 33 
#define ICON_EDITORAUTOCOMPLETE_OPERATOR 34
#define ICON_EDITORAUTOCOMPLETE_TYPEPARAMETER 35
#define ICON_EDITORSEARCHRESULTS_CLOSED 36
#define ICON_EDITORSEARCHRESULTS_OPENED 37
	 
#define ICON_EXPLORER_FOLDEROPEN 38
#define ICON_EXPLORER_FOLDERCLOSED 39
#define ICON_EXPLORER_FILE 40
	 
#define ICON_LSP_STANDBY 41
#define ICON_LSP_INITIALIZING 42
#define ICON_LSP_RUNNING 43
#define ICON_LSP_SHUTTINGDOWN 44
#define ICON_LSP_EXITED 45
#define ICON_LSP_CRASHED 46

#define ICON_COUNT 47

#ifndef INCLUDE_ONLY_ICON_IDS
struct ID2D1Bitmap;
struct ID2D1DeviceContext;
struct ID2D1SolidColorBrush;
struct D2D_POINT_2F;
union Color;

struct Icons {
	ID2D1Bitmap* iconAtlas = nullptr;
	
	bool Init(ID2D1DeviceContext* dc);
	void Shutdown();
	
	void DrawIcon(ID2D1DeviceContext* dc, int iconId, const D2D_POINT_2F& position, float widthAndHeight);
	void DrawIcon(ID2D1DeviceContext* dc, int iconId, const D2D_POINT_2F& position, float widthAndHeight, Color color);
};

extern Icons icons;

#endif
